"""D-FS — deterministic dependency-direction reconciliation from the trigger.

When a feature's ``invocation.trigger`` names another feature's id, that feature
consumes the named feature's output and therefore depends on it. These tests
cover the trigger-authoritative correction (D-FS2=B), the conservative
leave-untouched cases, whole-word id matching (D-FS3), mutual references handed
to the DAG pruner, and the end-to-end path through build_feature_specs.
"""

import json
from typing import Any
from unittest.mock import MagicMock, patch

from spec4.agents import feature_speccer


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _feat(fid: str, trigger: str = "", deps: list[str] | None = None) -> dict[str, Any]:
    return {
        "id": fid,
        "name": fid,
        "invocation": {"trigger": trigger} if trigger else {},
        "dependencies": list(deps or []),
    }


def _deps(features: list[dict[str, Any]]) -> dict[str, list[str]]:
    return {f["id"]: f["dependencies"] for f in features}


def _complete_returning(payload: Any) -> Any:
    resp = MagicMock()
    text = payload if isinstance(payload, str) else json.dumps(payload)
    resp.choices[0].message.content = f"```json\n{text}\n```"
    return patch("spec4.llm.complete", return_value=resp)


def _vision(*ids: str) -> dict[str, Any]:
    return {
        "vision_statement": {
            "name": "App",
            "vision": {
                "purpose": "p",
                "key_features_mvp": [{i: {"description": f"{i} desc"}} for i in ids],
            },
        }
    }


# ---------------------------------------------------------------------------
# The core correction (the Ragmeister case)
# ---------------------------------------------------------------------------


class TestReconcile:
    def test_inverted_edge_is_corrected(self) -> None:
        # policy_answers wrongly depends on source_links; source_links's trigger
        # names policy_answers, so the true edge is source_links -> policy_answers.
        features = [
            _feat("policy_answers", "An employee submits a question.",
                  deps=["source_links"]),
            _feat("source_links",
                  "An answer is generated by the policy_answers feature.",
                  deps=[]),
        ]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features) == {
            "policy_answers": [],
            "source_links": ["policy_answers"],
        }

    def test_already_consistent_is_untouched(self) -> None:
        # source_links already depends on policy_answers and the trigger agrees.
        features = [
            _feat("policy_answers", "User submits a question."),
            _feat("source_links", "policy_answers returns an answer.",
                  deps=["policy_answers"]),
        ]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features) == {
            "policy_answers": [],
            "source_links": ["policy_answers"],
        }

    def test_trigger_names_no_feature_is_noop(self) -> None:
        features = [
            _feat("a", "User clicks a button.", deps=[]),
            _feat("b", "A scheduled job runs.", deps=["a"]),
        ]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features) == {"a": [], "b": ["a"]}

    def test_self_reference_in_trigger_ignored(self) -> None:
        features = [_feat("a", "a is invoked again by a.", deps=[])]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features) == {"a": []}

    def test_missing_trigger_is_noop(self) -> None:
        features = [
            {"id": "a", "name": "a", "dependencies": []},
            {"id": "b", "name": "b", "invocation": {}, "dependencies": ["a"]},
        ]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features) == {"a": [], "b": ["a"]}


# ---------------------------------------------------------------------------
# Whole-word matching (D-FS3)
# ---------------------------------------------------------------------------


class TestWordBoundary:
    def test_substring_id_not_matched(self) -> None:
        # "qa" must not match inside "policy_qa" (underscore is a word char).
        features = [
            _feat("qa", "User opens the qa panel."),
            _feat("policy_qa", "User asks a question."),
            _feat("consumer", "policy_qa generates a result.", deps=[]),
        ]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features)["consumer"] == ["policy_qa"]

    def test_standalone_id_is_matched(self) -> None:
        features = [
            _feat("qa", "User asks a question."),
            _feat("consumer", "The qa step produces output.", deps=[]),
        ]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features)["consumer"] == ["qa"]


# ---------------------------------------------------------------------------
# Mutual references — additive, left to the pruner
# ---------------------------------------------------------------------------


class TestMutual:
    def test_mutual_references_kept_additive(self) -> None:
        # Each trigger names the other: ambiguous, so no reverse edge is removed;
        # both edges survive reconciliation and the DAG pruner resolves the cycle.
        features = [
            _feat("a", "b emits a value.", deps=[]),
            _feat("b", "a emits a value.", deps=[]),
        ]
        feature_speccer._reconcile_dependencies(features)
        assert _deps(features) == {"a": ["b"], "b": ["a"]}
        # The downstream pruner then breaks the cycle deterministically.
        feature_speccer._validate_dependencies(features)
        deps = _deps(features)
        assert not (deps["a"] and deps["b"])  # at most one edge survives


# ---------------------------------------------------------------------------
# End to end through build_feature_specs
# ---------------------------------------------------------------------------


class TestBuildIntegration:
    def test_build_corrects_inverted_edge(self) -> None:
        payload = {
            "features": [
                {
                    "id": "policy_answers",
                    "purpose": "Answer questions.",
                    "invocation": {"trigger": "An employee submits a question."},
                    "dependencies": ["source_links"],
                },
                {
                    "id": "source_links",
                    "purpose": "Cite sources.",
                    "invocation": {
                        "trigger": "An answer is generated by policy_answers."
                    },
                    "dependencies": [],
                },
            ],
            "nfr_goals": [],
        }
        with _complete_returning(payload):
            fs = feature_speccer.build_feature_specs(
                _vision("policy_answers", "source_links"), {"model": "x"}
            )
        by_id = {f["id"]: f["dependencies"] for f in fs["features"]}
        assert by_id == {"policy_answers": [], "source_links": ["policy_answers"]}
